// <auto-generated />
using System;
using DormMS.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DormMS.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260420174403_RestoreRoomTypes")]
    partial class RestoreRoomTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DormMS.Web.Models.Allocation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("actualCheckIn")
                        .HasColumnType("datetime2")
                        .HasColumnName("actual_check_in");

                    b.Property<DateTime?>("actualCheckOut")
                        .HasColumnType("datetime2")
                        .HasColumnName("actual_check_out");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("createdBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("endDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<bool>("isCurrent")
                        .HasColumnType("bit")
                        .HasColumnName("is_current");

                    b.Property<string>("keyCardNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("key_card_number");

                    b.Property<int>("roomId")
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    b.Property<decimal>("securityDeposit")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("security_deposit");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<int>("studentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("id");

                    b.HasIndex("roomId");

                    b.HasIndex("studentId");

                    b.ToTable("Allocations");

                    b.HasData(
                        new
                        {
                            id = 1,
                            createdAt = new DateTime(2026, 4, 20, 20, 44, 3, 270, DateTimeKind.Local).AddTicks(54),
                            isCurrent = true,
                            roomId = 1,
                            securityDeposit = 1000m,
                            startDate = new DateTime(2026, 2, 20, 20, 44, 3, 270, DateTimeKind.Local).AddTicks(57),
                            status = "Checked-In",
                            studentId = 1
                        });
                });

            modelBuilder.Entity("DormMS.Web.Models.AuditLog", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("entityId")
                        .HasColumnType("int");

                    b.Property<string>("entityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ipAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("newValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("oldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("userId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("userId");

                    b.ToTable("Audit_logs");
                });

            modelBuilder.Entity("DormMS.Web.Models.Building", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("buildingCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("building_code");

                    b.Property<string>("buildingName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("building_name");

                    b.Property<bool>("hasElevator")
                        .HasColumnType("bit")
                        .HasColumnName("has_elevator");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("totalFloors")
                        .HasColumnType("int")
                        .HasColumnName("total_floors");

                    b.HasKey("id");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            id = 1,
                            buildingCode = "A",
                            buildingName = "Alpha Block",
                            hasElevator = true,
                            status = "Active",
                            totalFloors = 4
                        });
                });

            modelBuilder.Entity("DormMS.Web.Models.Document", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("documentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("documentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("filePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("uploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("uploadedByUserId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("uploadedByUserId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("DormMS.Web.Models.Fee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("feeCategory")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fee_category");

                    b.Property<string>("feeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fee_name");

                    b.Property<bool>("isRecurring")
                        .HasColumnType("bit")
                        .HasColumnName("is_recurring");

                    b.Property<string>("recurrenceInterval")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("recurrence_interval");

                    b.HasKey("id");

                    b.ToTable("Fees");

                    b.HasData(
                        new
                        {
                            id = 1,
                            amount = 850m,
                            feeCategory = "Accommodation",
                            feeName = "Monthly Rent",
                            isRecurring = true
                        });
                });

            modelBuilder.Entity("DormMS.Web.Models.MaintenanceRequest", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("assignedTo")
                        .HasColumnType("int")
                        .HasColumnName("assigned_to");

                    b.Property<DateTime?>("completedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_date");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("issueCategory")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("issue_category");

                    b.Property<string>("priority")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("priority");

                    b.Property<DateTime?>("requestDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("request_date");

                    b.Property<string>("requestNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("request_number");

                    b.Property<int?>("roomId")
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("studentFeedback")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("student_feedback");

                    b.Property<int?>("studentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<int?>("studentRating")
                        .HasColumnType("int")
                        .HasColumnName("student_rating");

                    b.HasKey("id");

                    b.HasIndex("assignedTo");

                    b.HasIndex("roomId");

                    b.HasIndex("studentId");

                    b.ToTable("Maintenance_requests");
                });

            modelBuilder.Entity("DormMS.Web.Models.Notification", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("isRead")
                        .HasColumnType("bit")
                        .HasColumnName("is_read");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<string>("targetUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("target_url");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.Property<int>("userId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("id");

                    b.HasIndex("userId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("DormMS.Web.Models.Payment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("paymentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("payment_date");

                    b.Property<string>("paymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payment_method");

                    b.Property<string>("paymentReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payment_reference");

                    b.Property<int?>("receivedBy")
                        .HasColumnType("int")
                        .HasColumnName("received_by");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<int>("studentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<string>("transactionId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("transaction_id");

                    b.HasKey("id");

                    b.HasIndex("studentId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("DormMS.Web.Models.Penalty", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("appliedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("applied_date");

                    b.Property<string>("penaltyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("penalty_type");

                    b.Property<string>("reason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reason");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<int>("studentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("id");

                    b.HasIndex("studentId");

                    b.ToTable("Penalties");
                });

            modelBuilder.Entity("DormMS.Web.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("DormMS.Web.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("roleName");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Sistem yöneticisi",
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Yurt müdürü",
                            RoleName = "DormManager"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Öğrenci",
                            RoleName = "Student"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Personel / Tekniker",
                            RoleName = "Staff"
                        });
                });

            modelBuilder.Entity("DormMS.Web.Models.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("roleId");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnName("permissionId");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("Role_permissions");
                });

            modelBuilder.Entity("DormMS.Web.Models.Room", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("buildingId")
                        .HasColumnType("int")
                        .HasColumnName("building_id");

                    b.Property<int?>("capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("currentOccupancy")
                        .HasColumnType("int")
                        .HasColumnName("current_occupancy");

                    b.Property<int?>("floorNumber")
                        .HasColumnType("int")
                        .HasColumnName("floor_number");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<string>("roomNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("room_number");

                    b.Property<int?>("roomTypeId")
                        .HasColumnType("int")
                        .HasColumnName("room_type_id");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("id");

                    b.HasIndex("buildingId");

                    b.HasIndex("roomTypeId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            id = 1,
                            buildingId = 1,
                            capacity = 1,
                            createdAt = new DateTime(2026, 4, 20, 20, 44, 3, 270, DateTimeKind.Local).AddTicks(35),
                            currentOccupancy = 1,
                            floorNumber = 1,
                            roomNumber = "101",
                            roomTypeId = 1,
                            status = "Occupied",
                            updatedAt = new DateTime(2026, 4, 20, 20, 44, 3, 270, DateTimeKind.Local).AddTicks(38)
                        });
                });

            modelBuilder.Entity("DormMS.Web.Models.RoomType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("basePrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("base_price_per_month");

                    b.Property<int>("bedCount")
                        .HasColumnType("int")
                        .HasColumnName("bed_count");

                    b.Property<int>("capacity")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("hasAirConditioner")
                        .HasColumnType("bit")
                        .HasColumnName("has_air_conditioner");

                    b.Property<bool>("hasBathroom")
                        .HasColumnType("bit")
                        .HasColumnName("has_bathroom");

                    b.Property<string>("typeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type_name");

                    b.HasKey("id");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            id = 1,
                            basePrice = 1200m,
                            bedCount = 1,
                            capacity = 1,
                            description = "Premium privacy and high-end comfort.",
                            hasAirConditioner = false,
                            hasBathroom = true,
                            typeName = "Executive Single"
                        },
                        new
                        {
                            id = 2,
                            basePrice = 950m,
                            bedCount = 2,
                            capacity = 2,
                            description = "Perfect for friends and shared living.",
                            hasAirConditioner = false,
                            hasBathroom = true,
                            typeName = "Collaborative Twin"
                        },
                        new
                        {
                            id = 3,
                            basePrice = 750m,
                            bedCount = 3,
                            capacity = 3,
                            description = "Spacious shared living for groups.",
                            hasAirConditioner = false,
                            hasBathroom = true,
                            typeName = "Triple Shared"
                        },
                        new
                        {
                            id = 4,
                            basePrice = 600m,
                            bedCount = 4,
                            capacity = 4,
                            description = "Economical shared housing.",
                            hasAirConditioner = false,
                            hasBathroom = false,
                            typeName = "Standard Quad"
                        },
                        new
                        {
                            id = 5,
                            basePrice = 450m,
                            bedCount = 6,
                            capacity = 6,
                            description = "Affordable community living.",
                            hasAirConditioner = false,
                            hasBathroom = false,
                            typeName = "Budget Shared"
                        });
                });

            modelBuilder.Entity("DormMS.Web.Models.Student", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("city");

                    b.Property<string>("course")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("course");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("dateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("emergencyContactName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("emergency_contact_name");

                    b.Property<string>("emergencyContactPhone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("emergency_contact_phone");

                    b.Property<string>("emergencyContactRelationship")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("emergency_contact_relationship");

                    b.Property<string>("gender")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gender");

                    b.Property<string>("nationality")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nationality");

                    b.Property<int?>("roomId")
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("studentId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("student_id_number");

                    b.Property<string>("university")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("university");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("userId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int?>("yearOfStudy")
                        .HasColumnType("int")
                        .HasColumnName("year_of_study");

                    b.HasKey("id");

                    b.HasIndex("roomId");

                    b.HasIndex("userId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            id = 1,
                            createdAt = new DateTime(2026, 4, 20, 20, 44, 3, 269, DateTimeKind.Local).AddTicks(9964),
                            status = "Active",
                            studentId = "STU001",
                            updatedAt = new DateTime(2026, 4, 20, 20, 44, 3, 269, DateTimeKind.Local).AddTicks(9964),
                            userId = 3
                        });
                });

            modelBuilder.Entity("DormMS.Web.Models.StudentDocument", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("documentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("document_name");

                    b.Property<string>("documentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("document_type");

                    b.Property<string>("filePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file_path");

                    b.Property<int?>("fileSize")
                        .HasColumnType("int")
                        .HasColumnName("file_size");

                    b.Property<int>("studentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<DateTime>("uploadedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("uploaded_at");

                    b.HasKey("id");

                    b.HasIndex("studentId");

                    b.ToTable("Student_documents");
                });

            modelBuilder.Entity("DormMS.Web.Models.StudentFee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("dueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("due_date");

                    b.Property<int>("feeId")
                        .HasColumnType("int")
                        .HasColumnName("fee_id");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<int>("studentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("id");

                    b.HasIndex("feeId");

                    b.HasIndex("studentId");

                    b.ToTable("Student_fees");
                });

            modelBuilder.Entity("DormMS.Web.Models.SystemSetting", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("settingKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("settingValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("DormMS.Web.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("firstName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("firstName");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<DateTime?>("lastLogin")
                        .HasColumnType("datetime2")
                        .HasColumnName("lastLogin");

                    b.Property<string>("lastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lastName");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("passwordHash");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<string>("profilePicture")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("profilePicture");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            createdAt = new DateTime(2026, 4, 20, 20, 44, 3, 269, DateTimeKind.Local).AddTicks(9939),
                            email = "admin@dorm.com",
                            firstName = "System",
                            isActive = true,
                            lastName = "Admin",
                            passwordHash = "pmWkWSBCL51Bfkhn79xPuKBKHz//H6B+mY6G9/eieuM=",
                            updatedAt = new DateTime(2026, 4, 20, 20, 44, 3, 269, DateTimeKind.Local).AddTicks(9940),
                            username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            createdAt = new DateTime(2026, 4, 20, 20, 44, 3, 269, DateTimeKind.Local).AddTicks(9943),
                            email = "staff@dorm.com",
                            firstName = "John",
                            isActive = true,
                            lastName = "Staff",
                            passwordHash = "pmWkWSBCL51Bfkhn79xPuKBKHz//H6B+mY6G9/eieuM=",
                            updatedAt = new DateTime(2026, 4, 20, 20, 44, 3, 269, DateTimeKind.Local).AddTicks(9943),
                            username = "staff"
                        },
                        new
                        {
                            Id = 3,
                            createdAt = new DateTime(2026, 4, 20, 20, 44, 3, 269, DateTimeKind.Local).AddTicks(9945),
                            email = "student@dorm.com",
                            firstName = "Emily",
                            isActive = true,
                            lastName = "Resident",
                            passwordHash = "pmWkWSBCL51Bfkhn79xPuKBKHz//H6B+mY6G9/eieuM=",
                            updatedAt = new DateTime(2026, 4, 20, 20, 44, 3, 269, DateTimeKind.Local).AddTicks(9945),
                            username = "student"
                        });
                });

            modelBuilder.Entity("DormMS.Web.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("roleId");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("assignedAt");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("User_roles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1,
                            AssignedAt = new DateTime(2026, 4, 20, 20, 44, 3, 269, DateTimeKind.Local).AddTicks(9978)
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 4,
                            AssignedAt = new DateTime(2026, 4, 20, 20, 44, 3, 269, DateTimeKind.Local).AddTicks(9980)
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3,
                            AssignedAt = new DateTime(2026, 4, 20, 20, 44, 3, 269, DateTimeKind.Local).AddTicks(9981)
                        });
                });

            modelBuilder.Entity("DormMS.Web.Models.Allocation", b =>
                {
                    b.HasOne("DormMS.Web.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("roomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DormMS.Web.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("studentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DormMS.Web.Models.AuditLog", b =>
                {
                    b.HasOne("DormMS.Web.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("userId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DormMS.Web.Models.Document", b =>
                {
                    b.HasOne("DormMS.Web.Models.User", "Uploader")
                        .WithMany()
                        .HasForeignKey("uploadedByUserId");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("DormMS.Web.Models.MaintenanceRequest", b =>
                {
                    b.HasOne("DormMS.Web.Models.User", "Staff")
                        .WithMany()
                        .HasForeignKey("assignedTo");

                    b.HasOne("DormMS.Web.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("roomId");

                    b.HasOne("DormMS.Web.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("studentId");

                    b.Navigation("Room");

                    b.Navigation("Staff");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DormMS.Web.Models.Notification", b =>
                {
                    b.HasOne("DormMS.Web.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DormMS.Web.Models.Payment", b =>
                {
                    b.HasOne("DormMS.Web.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("studentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DormMS.Web.Models.Penalty", b =>
                {
                    b.HasOne("DormMS.Web.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("studentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DormMS.Web.Models.RolePermission", b =>
                {
                    b.HasOne("DormMS.Web.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DormMS.Web.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DormMS.Web.Models.Room", b =>
                {
                    b.HasOne("DormMS.Web.Models.Building", "Building")
                        .WithMany()
                        .HasForeignKey("buildingId");

                    b.HasOne("DormMS.Web.Models.RoomType", "RoomType")
                        .WithMany()
                        .HasForeignKey("roomTypeId");

                    b.Navigation("Building");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("DormMS.Web.Models.Student", b =>
                {
                    b.HasOne("DormMS.Web.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("roomId");

                    b.HasOne("DormMS.Web.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DormMS.Web.Models.StudentDocument", b =>
                {
                    b.HasOne("DormMS.Web.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("studentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DormMS.Web.Models.StudentFee", b =>
                {
                    b.HasOne("DormMS.Web.Models.Fee", "Fee")
                        .WithMany()
                        .HasForeignKey("feeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DormMS.Web.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("studentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fee");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DormMS.Web.Models.UserRole", b =>
                {
                    b.HasOne("DormMS.Web.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DormMS.Web.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DormMS.Web.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("DormMS.Web.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DormMS.Web.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
